#!/bin/bash
# Fetch the producer's signal file from S3 into the book runtime's state
# directory (bot-strategy#937). Runs from book-signal-fetch-<instance>.timer
# on the host as the book-runtime identity. Atomic: the download lands in a
# temp file next to the target and is renamed only if it parses as JSON
# and its payload changed, so the runtime never reads a half-written or
# byte-identical re-upload as a new file.
#
# <instance>.fetch.env, generated by install_book_runtime.sh out of the
# validated config, carries the values that let this script apply the same
# checks signal.rs will: BOOK_SIGNAL_MAX_AGE_SECS (freshness),
# BOOK_SIGNAL_PRODUCER_ID (producer identity) and BOOK_DECISION_TIME_UTC
# (the decision time a date-keyed schedule derives from decision_key, for
# the as_of look-ahead bound; empty for calendar schedules), plus the
# weight constraints BOOK_UNIVERSE / BOOK_MAX_SYMBOL_WEIGHT /
# BOOK_NET_TOLERANCE / BOOK_REQUIRE_DOLLAR_NEUTRAL, and the grid
# (BOOK_SCHEDULE_KIND / BOOK_ANCHOR_DATE / BOOK_EVERY_DAYS) that says
# which decision key is current. Any of them
# unset skips only its own check -- the runtime remains authoritative, the
# point here is to not displace a usable local file with one it will
# reject.
#
#   book_signal_fetch.sh s3://bucket/debot/book/xsmom-695/signal.json /var/lib/book-runtime/xsmom-695/signal.json
set -euo pipefail

SRC=${1:?s3 uri}
DST=${2:?destination path}
DIR=$(dirname "$DST")
TMP="$DIR/.signal.fetch.$$"
trap 'rm -f "$TMP"' EXIT

if ! aws s3 cp --only-show-errors "$SRC" "$TMP"; then
  echo "book_signal_fetch: download failed: $SRC" >&2
  exit 1
fi
# Full schema-v1 check plus the payload hash (same canonical form as
# scripts/book_signal_file.py / src/book/signal.rs) before the download can
# displace the last valid local file; a file the runtime would reject must
# never replace one it accepted.
if ! SUMMARY=$(BOOK_SIGNAL_MAX_AGE_SECS="${BOOK_SIGNAL_MAX_AGE_SECS:-}" \
  BOOK_SIGNAL_PRODUCER_ID="${BOOK_SIGNAL_PRODUCER_ID:-}" \
  BOOK_DECISION_TIME_UTC="${BOOK_DECISION_TIME_UTC:-}" \
  BOOK_MAX_SYMBOL_WEIGHT="${BOOK_MAX_SYMBOL_WEIGHT:-}" \
  BOOK_NET_TOLERANCE="${BOOK_NET_TOLERANCE:-}" \
  BOOK_REQUIRE_DOLLAR_NEUTRAL="${BOOK_REQUIRE_DOLLAR_NEUTRAL:-}" \
  BOOK_UNIVERSE="${BOOK_UNIVERSE:-}" \
  BOOK_SCHEDULE_KIND="${BOOK_SCHEDULE_KIND:-}" \
  BOOK_ANCHOR_DATE="${BOOK_ANCHOR_DATE:-}" \
  BOOK_EVERY_DAYS="${BOOK_EVERY_DAYS:-}" \
  python3 - "$TMP" <<'PY'
import hashlib, json, math, os, sys
from datetime import datetime, timedelta, timezone
def _reject_constant(token):
    raise SystemExit(f"non-standard JSON constant {token} (the runtime's parser rejects it)")
def _no_duplicate_keys(pairs):
    seen = set()
    for k, _ in pairs:
        if k in seen:
            # serde rejects a repeated struct field; Python would silently
            # keep the last one and promote a file the runtime cannot parse.
            raise SystemExit(f"duplicate JSON key {k!r}")
        seen.add(k)
    return dict(pairs)
d = json.load(
    open(sys.argv[1]),
    parse_constant=_reject_constant,
    object_pairs_hook=_no_duplicate_keys,
)
for k in ("schema_version", "producer_id", "generated_at", "as_of", "decision_key", "weights", "payload_sha256"):
    if k not in d:
        raise SystemExit(f"missing field {k}")
if isinstance(d["schema_version"], bool) or not isinstance(d["schema_version"], int) or d["schema_version"] != 1:
    raise SystemExit(f"schema_version must be the integer 1, got {d['schema_version']!r}")
for k in ("producer_id", "decision_key", "payload_sha256"):
    if not isinstance(d[k], str) or not d[k].strip():
        raise SystemExit(f"{k} must be a non-empty string")
ts = {}
for k in ("generated_at", "as_of"):
    if not isinstance(d[k], str):
        raise SystemExit(f"{k} must be a string timestamp")
    try:
        ts[k] = datetime.strptime(d[k], "%Y-%m-%dT%H:%M:%SZ")
    except ValueError as e:
        raise SystemExit(f"{k} is not a YYYY-MM-DDTHH:MM:SSZ timestamp: {e}")
if ts["as_of"] > ts["generated_at"]:
    raise SystemExit("as_of is after generated_at (look-ahead); the runtime would reject this file")
# The runtime refuses a file generated more than 60s in the future (a
# producer clock error); promoting it here would displace a usable signal
# and lose the window. Same bound, applied before the mv.
age = (datetime.now(timezone.utc).replace(tzinfo=None) - ts["generated_at"]).total_seconds()
if -age > 60:
    raise SystemExit(f"generated_at is {-age:.0f}s in the future; the runtime would reject this file")
want_producer = os.environ.get("BOOK_SIGNAL_PRODUCER_ID", "").strip()
if want_producer and d["producer_id"] != want_producer:
    # A routing mistake upstream must not displace this instance's signal.
    raise SystemExit(f"producer_id {d['producer_id']!r} != configured {want_producer!r}")
kind = os.environ.get("BOOK_SCHEDULE_KIND", "").strip()
decision_time = os.environ.get("BOOK_DECISION_TIME_UTC", "").strip()
if decision_time and kind in ("interval_days", "daily"):
    # The runtime only accepts the key of the decision that is current at
    # the time it reads the file. Accept that key or the next one (the
    # producer publishes a few minutes before the decision instant); any
    # other date-shaped key -- a regenerated previous grid date, say --
    # would be refused by the runtime and must not displace a usable file.
    hh, mm = (int(x) for x in decision_time.split(":"))
    now_utc = datetime.now(timezone.utc).replace(tzinfo=None)
    today = now_utc.date()
    if kind == "daily":
        cur = today if now_utc.time() >= datetime(2000, 1, 1, hh, mm).time() else today - timedelta(days=1)
        nxt = cur + timedelta(days=1)
    else:
        anchor_s = os.environ.get("BOOK_ANCHOR_DATE", "").strip()
        every = int(os.environ.get("BOOK_EVERY_DAYS", "0") or 0)
        if not anchor_s or every <= 0:
            raise SystemExit("interval_days schedule without BOOK_ANCHOR_DATE/BOOK_EVERY_DAYS")
        anchor = datetime.strptime(anchor_s, "%Y-%m-%d").date()
        delta = (today - anchor).days
        if delta < 0:
            cur, nxt = None, anchor
        else:
            aligned = anchor + timedelta(days=(delta // every) * every)
            if aligned == today and now_utc.time() < datetime(2000, 1, 1, hh, mm).time():
                aligned = aligned - timedelta(days=every)
            cur = aligned if aligned >= anchor else None
            nxt = (cur + timedelta(days=every)) if cur else anchor
    allowed = {k.isoformat() for k in (cur, nxt) if k}
    if d["decision_key"] not in allowed:
        raise SystemExit(
            f"decision_key {d['decision_key']} is not the current or next decision ({', '.join(sorted(allowed))})"
        )
if decision_time:
    # Date-keyed schedules: decision_key IS the decision date, so the
    # decision instant is derivable here and as_of must not be after it.
    try:
        hh, mm = (int(x) for x in decision_time.split(":"))
        day = datetime.strptime(d["decision_key"], "%Y-%m-%d")
    except ValueError as e:
        raise SystemExit(f"cannot derive the decision time from {d['decision_key']!r} + {decision_time!r}: {e}")
    decision_at = day.replace(hour=hh, minute=mm)
    if ts["as_of"] > decision_at:
        raise SystemExit(
            f"as_of {d['as_of']} is after the {d['decision_key']} decision at {decision_at:%H:%M}Z (look-ahead)"
        )
max_age = os.environ.get("BOOK_SIGNAL_MAX_AGE_SECS", "").strip()
if max_age:
    if age > int(max_age):
        # An S3 rollback or a lagging producer must not displace a signal
        # the runtime can still use.
        raise SystemExit(f"generated_at is {age:.0f}s old, past the {max_age}s bound")
else:
    print("book_signal_fetch: BOOK_SIGNAL_MAX_AGE_SECS unset; age check skipped", file=sys.stderr)
if not isinstance(d["weights"], dict):
    raise SystemExit("weights must be a symbol -> number mapping")
for sym, v in d["weights"].items():
    if not isinstance(sym, str) or not sym.strip():
        raise SystemExit(f"bad symbol key {sym!r}")
    if isinstance(v, bool) or not isinstance(v, (int, float)) or not math.isfinite(float(v)):
        raise SystemExit(f"weight for {sym} must be a finite number, got {v!r}")
payload = {"as_of": d["as_of"], "decision_key": d["decision_key"], "producer_id": d["producer_id"],
           "weights": {k: float(v) for k, v in d["weights"].items()}}
sha = hashlib.sha256(json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
if sha != str(d["payload_sha256"]).lower():
    raise SystemExit(f"payload_sha256 mismatch: file {d['payload_sha256']} computed {sha}")
# The weight constraints signal.rs enforces. Each is skipped when its
# value is absent, but the installer always writes them.
universe = {s for s in os.environ.get("BOOK_UNIVERSE", "").split(",") if s}
if universe:
    outside = sorted(set(d["weights"]) - universe)
    if outside:
        raise SystemExit(f"weights name {len(outside)} symbol(s) outside the universe: {', '.join(outside)}")
max_w = os.environ.get("BOOK_MAX_SYMBOL_WEIGHT", "").strip()
if max_w:
    cap = float(max_w)
    over = sorted(s for s, w in d["weights"].items() if abs(float(w)) > cap + 1e-12)
    if over:
        raise SystemExit(f"weights over the {cap} per-symbol cap: {', '.join(over)}")
gross = sum(abs(float(w)) for w in d["weights"].values())
if gross > 1.0 + 1e-9:
    raise SystemExit(f"sum |w| = {gross:.6f} > 1")
neutral = os.environ.get("BOOK_REQUIRE_DOLLAR_NEUTRAL", "").strip().lower() == "true"
tol = os.environ.get("BOOK_NET_TOLERANCE", "").strip()
if neutral and tol:
    net = sum(float(w) for w in d["weights"].values())
    if abs(net) > float(tol) + 1e-12:
        raise SystemExit(f"|net| = {abs(net):.6f} > net_tolerance {tol}")
print(f"{d['decision_key']} {sha[:12]} n={len(d['weights'])}")
PY
); then
  echo "book_signal_fetch: $SRC failed schema/hash validation; keeping the current file" >&2
  exit 1
fi
if [ -f "$DST" ] && cmp -s "$TMP" "$DST"; then
  exit 0
fi
chmod 0640 "$TMP"
mv -f "$TMP" "$DST"
echo "book_signal_fetch: updated $DST ($SUMMARY)"
